/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author danie
 */
public class adn1 extends javax.swing.JFrame {

    /**
     * Creates new form adn1
     */
    public adn1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegresarCrearv = new javax.swing.JButton();
        jButtonCrearA = new javax.swing.JButton();
        jTextFieldV1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldV2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Crear Tanques");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(".");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("\"DECODIFICADOR ADN\"");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 490, 60));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("----Resultado---");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("= ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        jButtonRegresarCrearv.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegresarCrearv.setFont(new java.awt.Font("Dubai", 3, 36)); // NOI18N
        jButtonRegresarCrearv.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresarCrearv.setText("Regresar");
        jButtonRegresarCrearv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarCrearvActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresarCrearv, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 180, 50));

        jButtonCrearA.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearA.setFont(new java.awt.Font("Dubai", 3, 48)); // NOI18N
        jButtonCrearA.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrearA.setText("Procesar");
        jButtonCrearA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearAActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearA, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 340, 90));

        jTextFieldV1.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV1.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 310, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese ADN 2:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 250, 60));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ingrese ADN 1:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 290, 50));

        jTextFieldV2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldV2.setFont(new java.awt.Font("Ebrima", 3, 24)); // NOI18N
        jTextFieldV2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldV2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 310, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/adn22.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 526));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV1ActionPerformed

    private void jTextFieldV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldV2ActionPerformed

    private void jButtonRegresarCrearvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarCrearvActionPerformed
        // TODO add your handling code here:
      
        initComponents();
         this.setLocationRelativeTo(null);
        setSize(1490, 1200);
        setTitle("DECODIFICADOR ADN");
        this.setVisible(false);

        new adn ().setVisible(true);

        setSize(1290, 1000);
        dispose();
        
    }//GEN-LAST:event_jButtonRegresarCrearvActionPerformed

    private void jButtonCrearAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearAActionPerformed
        // TODO add your handling code here:
      //  JuegoTableros entrada2 = new JuegoTableros();
        //entrada2.show();
        //entrada2.setSize(1290, 1000);
        //dispose();

        
    }//GEN-LAST:event_jButtonCrearAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adn1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adn1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearA;
    private javax.swing.JButton jButtonRegresarCrearv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldV1;
    private javax.swing.JTextField jTextFieldV2;
    // End of variables declaration//GEN-END:variables
}
